[profile.default]
src = "src"
out = "out"
script = "script"
test = "test"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.28"
gas_reports = ["*"]
fuzz = { runs = 1_000 }

[profile.coverage]
ignore = ["test/*", "script/*"]

[invariant]
memory_allocation = "1000000000" # ~1GB

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
