[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
gas_reports = ["PaymentVault", "DataPayments"]
gas_limit = "18446744073709551615" # u64::MAX

[fuzz]
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

